---
- name: Update apt
  apt: update_cache=yes cache_valid_time=86400

- name: Install uber text editors
  apt:
    state: latest
    name:
      - vim

- name: run vim vundle install
  become: no
  command: vim +'silent! BundleInstall' +qa

- name: initialize coc plugin
  become: no
  command: ~/.local/bin/yarn install
  args:
    creates: ~/.vim/bundle/coc.nvim/node_modules
    chdir: ~/.vim/bundle/coc.nvim
