---
- name: Install uber text editors
  package:
    state: latest
    name:
      - vim

- name: run vim-plug install
  become: no
  command: vim +'silent! PlugInstall' +qa
  environment:
    PATH: /home/{{ansible_user}}/.local/bin:/usr/bin:/usr/local/bin
