---
- name: Update apt
  apt: update_cache=yes cache_valid_time=86400

- name: Install uber text editors
  apt:
    state: latest
    name:
      - vim

- name: run vim vundle install
  become: no
  command: vim +'silent! BundleInstall' +qa

- name: compile YouCompleteMe plugin
  become: no
  command: ./install.py
  args:
    chdir: ~/.vim/bundle/YouCompleteMe/
    creates: ~/.vim/bundle/YouCompleteMe/third_party/ycmd/ycm_core.so
