---
- name: import system specific variables
  include_vars: "{{ ansible_distribution }}.yml"

- name: Install uber text editors
  package:
    state: latest
    name:
      - "{{ package.vim }}"

- name: prepare directory for coc plugin
  become: no
  file:
    path: /home/{{ansible_user}}/.config/coc
    state: directory

- name: run vim-plug install
  become: no
  command: vim +'silent! PlugInstall' +qa
  environment:
    PATH: /home/{{ansible_user}}/.local/bin:/usr/bin:/usr/local/bin
