---
- name: Update apt
  apt: update_cache=yes cache_valid_time=86400

- name: Install common tools
  apt:
    state: latest
    name:
      - zsh
      - tmux
      - screen
      - cowsay
      - sc
      - weechat
      - figlet
      - tidy

- name: install antibody for zsh
  shell: curl -sL git.io/antibody | sh -s

- name: choose shell
  user:
    name: "{{ansible_user}}"
    shell: /usr/bin/zsh
