---
- name: Update apt
  apt: update_cache=yes cache_valid_time=86400

- name: Install common tools
  apt: name={{ item }} state=latest
  with_items:
    - zsh
    - tmux
    - screen
    - caca-utils
    - cowsay
    - sc
    - weechat
    - wicd-curses
    - figlet
    - tidy

- name: install antibody for zsh
  shell: curl -sL git.io/antibody | sh -s

- name: choose shell
  user: name=borsuk shell=/usr/bin/zsh
