---
- name: Install rxvt terminal emulator and used packages
  package:
    state: latest
    name:
      - rxvt-unicode-256color

- name: x-terminal set
  shell: update-alternatives --set x-terminal-emulator /usr/bin/urxvt

