---
- name: Install rxvt terminal emulator and used packages
  when: ansible_facts['distribution'] == "Ubuntu"
  package:
    state: latest
    name:
      - rxvt-unicode-256color

- name: x-terminal set
  when: ansible_facts['distribution'] == "Ubuntu"
  shell: update-alternatives --set x-terminal-emulator /usr/bin/urxvt


- name: Install rxvt terminal emulator and used packages
  when: ansible_facts['distribution'] == "Archlinux"
  package:
    state: latest
    name:
      - rxvt-unicode

