---
- name: One shot developer system setup
  hosts: all
  become: yes
  become_method: su
  roles:
    - system
    - dotfiles
    - aria
    - shell
    - python
    - web
    - editor
    - ranger
    - general-tools
    - i3wm
    - browser
    - java
    - virtuals
    - remote
    - music
    - rxvt
    - video
    - ide

#- name: restart machine
  #command: shutdown -r now "Ansible updates triggered"
