---
- name: Prepare basic env for symfony2 app on all nodes
  hosts: all
  remote_user: borsuk
  sudo: yes
  vars_files:
    - variables.yml
  roles:
    - system
    - dotfiles
    - aria
    - shell
    - editor
    - ranger
    - general-tools
    - i3wm
    - browser
    - music
    - rxvt
    - video

#- name: restart machine
  #command: shutdown -r now "Ansible updates triggered"
