---
- name: Update apt
  apt: update_cache=yes cache_valid_time=86400

- name: Install virtual environments
  apt:
    state: latest
    name:
      - virtualbox
      - docker.io

- name: download vagrant package
  get_url: url=https://releases.hashicorp.com/vagrant/2.2.5/vagrant_2.2.5_x86_64.deb dest=/tmp/vagrant.deb

- name: install vagrant
  command: gdebi --n /tmp/vagrant.deb
