---
- name: Update apt
  apt: update_cache=yes cache_valid_time=86400

- name: Install common tools
  apt:
    state: latest
    name:
      - pass
      - gnupg2
      - gnupg-agent
      - redshift
      - udevil
      - wakeonlan
      - wvdial
      - xdotool
      - xpad
      - wget
      - screenkey
