---
- name: Install common tools
  package:
    state: latest
    name:
      - pass
      - gnupg2
      - gnupg-agent
      - redshift
      - udevil
      - wakeonlan
      - wvdial
      - xdotool
      - xpad
      - wget
      - screenkey
