---
- name: Update apt
  apt: update_cache=yes cache_valid_time=86400

- name: Install common tools
  apt: name={{ item }} state=latest
  with_items:
    - pass
    - gnupg2
    - gnupg-agent
    - redshift
    - udevil
    - wakeonlan
    - wvdial
    - xdotool
    - xpad
    - wget

- name: prepare dir for screenkey
  become: no
  file: path='~/expr/screenkey' state=directory

- name: Install screenkey
  become: no
  unarchive:
    src: https://github.com/wavexx/screenkey/archive/screenkey-0.9.tar.gz
    dest: ~/expr/screenkey
    remote_src: yes

