---
- name: Install stow
  apt: name=stow state=latest

- name: Ensure the .ssh, workspace, etc. directories exists
  sudo: no
  file: path={{item.path}} state=directory
  with_items:
    - { path: '~/.ssh' }
    - { path: '~/workspace' }
    - { path: '~/.fonts' }
    - { path: '~/bin' }

- name: Add ssh config with your keys to access all repositories
  sudo: no
  copy: src={{item.src}} dest=~/.ssh/ mode=0600
  with_items:
    - { src: '~/.ssh/id_rsa.pub'}
    - { src: '~/.ssh/id_rsa'}

- name: Grab dotfiles git repo - this is a crucial step will be required by others
  sudo: no
  git:
    repo: "git@bitbucket.com:wielkiborsuk/dotfiles.git"
    dest: "~/.dotfiles"
    accept_hostkey: yes
    update: yes

- name: remove .Xdefaults to allow rxvt stowing
  file: path=/home/borsuk/.Xdefaults state=absent
  file: path=/home/borsuk/.gitconfig state=absent

- name: link config files
  sudo: no
  shell: stow -R {{ item }}
  args:
    chdir: ~/.dotfiles
  with_items:
    - stow
    - dunst
    - git
    - i3
    - ranger
    - rxvt
    - vundle-vim
    - zsh

- name: enable bitmap fonts
  file: path=/etc/fonts/conf.d/70-no-bitmaps.conf state=absent

- name: Grab smalls git repo - contains commands used by desktop setup
  sudo: no
  git:
    repo: "git@bitbucket.com:wielkiborsuk/smalls.git"
    dest: "~/workspace/smalls"
    accept_hostkey: yes
    update: yes

- name: link commands from smalls
  sudo: no
  shell: stow -R -t ~/ {{ item }}
  args:
    chdir: ~/workspace/smalls
  with_items:
    - album_converter
    - gmailcheck
    - pomodoro

      #append to the end of sudoers file
#ALL ALL=(root) NOPASSWD: /sbin/poweroff
#ALL ALL=(root) NOPASSWD: /sbin/reboot

