---
- name: Ensure the .ssh, workspace, etc. directories exists
  sudo: no
  file: path={{item.path}} state=directory
  with_items:
    - { path: '~/.ssh' }
    - { path: '~/workspace' }
    - { path: '~/.fonts' }
    - { path: '~/bin' }

- name: Add ssh config with your keys to access all repositories
  sudo: no
  copy: src={{item.src}} dest=~/.ssh/
  with_items:
    - { src: '~/.ssh/id_rsa.pub'}
    - { src: '~/.ssh/id_rsa'}

- name: Grab dotfiles git repo - this is a crucial step will be required by others
  sudo: no
  git:
    repo: "git@bitbucket.com:wielkiborsuk/dotfiles.git"
    dest: "~/workspace/dotfiles"
    accept_hostkey: yes
    update: yes

- name: link config files
  sudo: no
  file: src=~/workspace/dotfiles/{{item.src}} dest=~/{{item.dest}} state=link force=yes
  with_items:
    - { src: 'dunst/HOME..config/dunst', dest: '.config/dunst'}
    - { src: 'git/HOME..gitconfig', dest: '.gitconfig'}
    - { src: 'git/HOME..gitignore', dest: '.gitignore'}
    - { src: 'i3/HOME..config/i3status', dest: '.config/i3status'}
    - { src: 'i3/HOME..i3', dest: '.i3'}
    - { src: 'i3/HOME..tmux.conf', dest: '.tmux.conf'}
    - { src: 'ranger/HOME..config/ranger', dest: '.config/ranger'}
    - { src: 'rxvt/HOME..Xdefaults', dest: '.Xdefaults'}
    - { src: 'zsh', dest: '.zsh'}
    - { src: 'vundle-vim/HOME..vimrc', dest: '.vimrc'}
    - { src: 'vundle-vim/HOME..fonts/terminus', dest: '.fonts/terminus'}

- name: link config files
  sudo: no
  file: src=~/workspace/dotfiles/i3/HOME.bin/{{item.src}} dest=~/bin/{{item.src}} state=link force=yes
  with_items:
    - { src: 'cmus_status' }
    - { src: 'console_setup' }
    - { src: 'crestore' }
    - { src: 'i3conky' }
    - { src: 'i3exit' }
    - { src: 'i3lock' }
    - { src: 'trestore' }

- name: additional zsh link
  sudo: no
  file: src=~/.zsh/zshrc dest=~/.zshrc state=link force=yes

- name: enable bitmap fonts
  sudo: yes
  file: path=/etc/fonts/conf.d/70-no-bitmaps.conf state=absent

- name: Grab smalls git repo - contains commands used by desktop setup
  sudo: no
  git:
    repo: "git@bitbucket.com:wielkiborsuk/smalls.git"
    dest: "~/workspace/smalls"
    accept_hostkey: yes
    update: yes

- name: link commands from smalls
  sudo: no
  file: src=~/workspace/smalls/{{item.src}} dest=~/bin/{{item.name}} state=link force=yes
  with_items:
    - { src: 'album_converter/album_converter.py', name: 'album_converter.py' }
    - { src: 'gmailcheck/checker.py', name: 'checker.py' }
    - { src: 'gmailcheck/passstore.py', name: 'passstore.py' }
    - { src: 'pomodoro/pomodoro', name: 'pomodoro' }
    - { src: 'youtube_ripper/youtube_ripper.py', name: 'youtube_ripper.py' }

- name: link pomodoro audio file
  sudo: no
  file: src=~/workspace/smalls/pomodoro/ring.mp3 dest=~/.config/ring.mp3 state=link force=yes

      #append to the end of sudoers file
#ALL ALL=(root) NOPASSWD: /sbin/poweroff
#ALL ALL=(root) NOPASSWD: /sbin/reboot

