--- 
- name: Update apt
  apt: update_cache=yes cache_valid_time=86400

- name: Install python packages
  apt: name={{ item }} state=latest
  with_items:
    - python-dev
    - python-pip
    - python-crypto
    - python3-dev
    - python3-pycurl
    - python3-crypto
    - python3-pip
    - ipython
    - dreampie
    - bpython-urwid
    - cython
