---
- name: Install python packages
  when: ansible_facts['distribution'] == "Ubuntu"
  package:
    state: latest
    name:
      - python3-dev
      - python3-pycurl
      - python3-pip
      - python3-venv
      - python-is-python3

- name: Install python packages
  when: ansible_facts['distribution'] == "Archlinux"
  package:
    state: latest
    name:
      - python-pycurl
      - python-crypto
      - python-pip

- name: create default python interpreter link
  file:
    src: /usr/bin/python3
    dest: /usr/bin/python
    state: link
