---
- name: Install python packages
  when: ansible_facts['distribution'] == "Ubuntu"
  package:
    state: latest
    name:
      - python3-dev
      - python3-pycurl
      - python3-crypto
      - python3-pip

- name: Install python packages
  when: ansible_facts['distribution'] == "Archlinux"
  package:
    state: latest
    name:
      - python-pycurl
      - python-crypto
      - python-pip
