---
- name: Update apt
  apt: update_cache=yes cache_valid_time=86400

- name: Install python packages
  apt:
    state: latest
    name:
      - python3-dev
      - python3-pycurl
      - python3-crypto
      - python3-pip
