---
- name: Install common tools
  package:
    state: latest
    name:
      - atool
      - highlight
      - mediainfo
      - unrar
      - p7zip
      - w3m
      - zathura
      - zip
      - unzip


- name: Install w3m image support
  when: ansible_facts['distribution'] == "Ubuntu"
  package:
    state: latest
    name:
      - w3m-img
      - zathura-pdf-poppler

- name: Install w3m image support
  when: ansible_facts['distribution'] == "Archlinux"
  package:
    state: latest
    name:
      - imlib2
      - zathura-pdf-mupdf

- name: ensure that ~/expr exists
  become: no
  file: path=~/expr state=directory

- name: clone ranger repo
  become: no
  git:
    repo: 'https://github.com/ranger/ranger.git'
    dest: '~/expr/ranger'
    accept_hostkey: yes
    update: yes

- name: link ranger executable
  become: no
  file: src=~/expr/ranger/ranger.py dest=~/bin/ranger state=link force=yes
