---
- name: Update apt
  apt: update_cache=yes

- name: Install common tools
  apt: name={{ item }} state=latest
  with_items:
    - ranger
    - atool
    - highlight
    - mediainfo
    - rar
    - unrar
    - p7zip
    - w3m
