---
- name: Update apt
  apt: update_cache=yes cache_valid_time=86400

- name: Install common tools
  apt: name={{ item }} state=latest
  with_items:
    - atool
    - highlight
    - mediainfo
    - rar
    - unrar
    - p7zip
    - w3m

- name: ensure that ~/expr exists
  sudo: no
  file: path=~/expr state=directory

- name: clone ranger repo
  sudo: no
  git:
    repo: 'git://git.savannah.nongnu.org/ranger.git'
    dest: '~/expr/ranger'
    accept_hostkey: yes
    update: yes

- name: link ranger executable
  sudo: no
  file: src=~/expr/ranger/ranger.py dest=~/bin/ranger state=link force=yes
