---
- name: Install common tools
  package:
    state: latest
    name:
      - atool
      - highlight
      - mediainfo
      - rar
      - unrar
      - p7zip
      - w3m
      - zathura

- name: ensure that ~/expr exists
  become: no
  file: path=~/expr state=directory

- name: clone ranger repo
  become: no
  git:
    repo: 'git://git.savannah.nongnu.org/ranger.git'
    dest: '~/expr/ranger'
    accept_hostkey: yes
    update: yes

- name: link ranger executable
  become: no
  file: src=~/expr/ranger/ranger.py dest=~/bin/ranger state=link force=yes
