- name: enable sudo with no password for yaourt use
  template:
    src: easy-sudo
    dest: /etc/sudoers.d/easy-sudo
    validate: /usr/sbin/visudo -cf %s

- include_role:
    name: archlinux_aur
    apply:
      become: false
      vars:
        archlinux_aur_pkgs:
          - package-query
          - yaourt
          - task-spooler
        archlinux_aur_user: borsuk

- name: disable nopasswd sudo
  file:
    path: /etc/sudoers.d/easy-sudo
    state: absent

- name: install tools possibly missing from raw archlinux
  package:
    state: latest
    name:
      - dhcpcd
      - openssh

- name: enable services
  command:
    cmd: systemctl enable {{ item }}
  with_items:
    - dhcpcd
    - sshd

- name: create swapfile
  command: dd if=/dev/zero of=/swapfile bs=1048576 count=2048

- name: set proper file access for swapfile
  file:
    path: /swapfile
    mode: 0600

- name: prepare swap configuration
  command: mkswap /swapfile

- name: turn swap on for current session
  command: swapon /swapfile

- name: create fstab entry for swapfile
  lineinfile:
    path: /etc/fstab
    line: /swapfile    none    swap    sw    0    0

- name: adjust swappiness to put less load on swap file
  template:
    src: 90-low-sappiness.conf
    dest: /etc/sysctl.d/90-low-swappiness.conf
