- name: enable sudo with no password for yaourt use
  template:
    src: easy-sudo
    dest: /etc/sudoers.d/easy-sudo
    validate: /usr/sbin/visudo -cf %s

- include_role:
    name: archlinux_aur
    apply:
      become: false
      vars:
        archlinux_aur_pkgs:
          - package-query
          - yaourt
          - task-spooler
        archlinux_aur_user: borsuk

- name: disable nopasswd sudo
  file:
    path: /etc/sudoers.d/easy-sudo
    state: absent
