---
- name: import system specific variables
  include_vars: "{{ ansible_distribution }}.yml"

- name: Refresh pacman repositories
  when: ansible_facts['distribution'] == "Archlinux"
  pacman:
    update_cache: yes

- name: Refresh apt repositories
  when: ansible_facts['distribution'] == "Ubuntu"
  apt:
    update_cache: yes

- name: Install debian system tools
  when: ansible_facts['distribution'] == "Ubuntu"
  package:
    state: latest
    name:
      - gdebi
      - aptitude
      - pkg-config

- name: Install build tools
  package:
    state: latest
    name:
      - "{{ package.devel }}"
      - automake
      - autoconf
      - bison
      - cmake
      - curl

- name: Install admin tools
  package:
    state: latest
    name:
      - "{{ package.searcher }}"
      - ccze
      - git
      - htop

- name: run Arch specific tasks
  when: ansible_facts['distribution'] == "Archlinux"
  include_tasks: "{{ ansible_distribution }}.yml"
