---
- name: Install system tools
  package:
    state: latest
    name:
      - gdebi
      - htop

- name: Install build tools
  package:
    state: latest
    name:
      - build-essential
      - automake
      - autoconf
      - bison
      - cmake
      - curl

- name: Install admin tools
  package:
    state: latest
    name:
      - silversearcher-ag
      - ccze
      - git

- name: Install ansible preconditions
  package:
    state: latest
    name:
      - python-pycurl
