---
- name: Install system tools
  apt:
    state: latest
    name:
      - aptitude
      - gdebi
      - htop

- name: Install build tools
  apt:
    state: latest
    name:
      - build-essential
      - automake
      - autoconf
      - bison
      - cmake
      - curl

- name: Install admin tools
  apt:
    state: latest
    name:
      - silversearcher-ag
      - ccze
      - git

- name: Install ansible preconditions
  apt:
    state: latest
    name:
      - python-pycurl

- name: Update apt
  apt: update_cache=yes upgrade=yes cache_valid_time=86400
