---
- name: import system specific variables
  include_vars: "{{ ansible_distribution }}.yml"

- name: Install debian system tools
  when: ansible_facts['distribution'] == "Ubuntu"
  package:
    state: latest
    name:
      - gdebi

- name: Install build tools
  package:
    state: latest
    name:
      - "{{ package.devel }}"
      - automake
      - autoconf
      - bison
      - cmake
      - curl

- name: Install admin tools
  package:
    state: latest
    name:
      - "{{ package.searcher }}"
      - ccze
      - git
      - htop

- name: Install ansible preconditions
  package:
    state: latest
    name:
      - python-pycurl

- name: run Arch specific tasks
  when: ansible_facts['distribution'] == "Archlinux"
  import: "{{ ansible_distribution }}.yml"
