---
- name: Install system tools
  apt: name={{ item }} state=latest
  with_items:
    - aptitude
    - gdebi
    - htop

- name: add ansible repo
  apt_repository: repo='ppa:ansible/ansible' state=present

- name: Install build tools
  apt: name={{ item }} state=latest
  with_items:
    - build-essential
    - automake
    - autoconf
    - bison
    - cmake
    - ansible

- name: Install admin tools
  apt: name={{ item }} state=latest
  with_items:
    - ack-grep
    - silversearcher-ag
    - ccze
    - git
    - git-flow
    - hdup

- name: Install ansible preconditions
  apt: name={{ item }} state=latest
  with_items:
    - python-pycurl

- name: Update apt
  apt: update_cache=yes upgrade=yes cache_valid_time=86400
