---
- name: Update apt
  apt: update_cache=yes

- name: Install common tools
  apt: name={{ item }} state=latest
  with_items:
    - chromium-browser
    - chromium-codecs-ffmpeg-extra
    - flashplugin-installer
    - dillo
    - links
