---
- name: add i3 repo keyring
  command: /usr/lib/apt/apt-helper download-file http://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2018.01.30_all.deb keyring.deb SHA256:baa43dbbd7232ea2b5444cae238d53bebb9d34601cc000e82f11111b1889078a

- name: add keyring package
  command: dpkg -i ./keyring.deb

- name: add i3 repository
  apt_repository: repo='deb http://debian.sur5r.net/i3/ bionic universe' state=present

- name: Update apt
  apt: update_cache=yes cache_valid_time=86400

- name: Install common tools
  apt: name={{ item }} state=latest
  with_items:
    - i3
    - conky
    - dunst
    - feh
    - scrot
    - suckless-tools
    - xbacklight
