---
- name: Install common tools
  package:
    state: latest
    name:
      - conky
      - dunst
      - feh
      - scrot

- name: Install common tools
  when: ansible_facts['distribution'] == "Ubuntu"
  package:
    state: latest
    name:
      - suckless-tools
      - xbacklight
      - i3
      - libnotify4
      - libnotify-bin

- name: Install common tools
  when: ansible_facts['distribution'] == "Archlinux"
  package:
    state: latest
    name:
      - dmenu
      - xorg-xbacklight
      - i3-wm
      - i3lock
      - i3status
      - i3blocks
      - libnotify
