---
- name: add i3 repo keyring
  command: /usr/lib/apt/apt-helper download-file https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2019.02.01_all.deb keyring.deb SHA256:176af52de1a976f103f9809920d80d02411ac5e763f695327de9fa6aff23f416

- name: add keyring package
  command: dpkg -i ./keyring.deb

- name: add i3 repository
  apt_repository: repo='deb http://debian.sur5r.net/i3/ bionic universe' state=present

- name: Update apt
  apt: update_cache=yes cache_valid_time=86400

- name: Install common tools
  apt:
    state: latest
    name:
      - i3
      - conky
      - dunst
      - feh
      - scrot
      - suckless-tools
      - xbacklight
