---
- name: Update apt
  apt: update_cache=yes

- name: Install common tools
  apt: name={{ item }} state=latest
  with_items:
    - i3
    - conky
    - dmenu
    - dunst
    - feh
    - scrot
    - suckless-tools
