---
- name: Update apt
  apt: update_cache=yes

- name: Install nodejs
  apt:
    state: latest
    name:
      - nodejs
      - npm

- name: configure npm to use local directory for global installs
  become: no
  shell: npm config set prefix ~/.local

- name: install npm tools common for development process
  become: no
  npm: name={{ item }} global=yes
  with_items:
    - bower
    - forever
    - git-run
    - yarn
    - firebase-tools
