---
- name: Update apt
  apt: update_cache=yes cache_valid_time=86400

- name: Install common tools
  apt:
    state: latest
    name:
      - aria2

- name: Ensure expr directory in homedir
  become: no
  file: path={{item.path}} state=directory
  with_items:
    - { path: '~/expr' }
    - { path: '~/bin' }

- name: Checkout the diana project
  become: no
  git:
    repo: "https://github.com/baskerville/diana.git"
    dest: "~/expr/diana"
    accept_hostkey: yes
    update: yes

- name: Link diana binaries
  become: no
  file: src=~/expr/diana/{{item.name}} dest=~/bin/{{item.name}} state=link force=yes
  with_items:
    - { name: 'diana' }
    - { name: 'dad' }
