---
- name: Download intellij
  become: no
  get_url:
    url=https://download-cf.jetbrains.com/idea/ideaIU-2019.2.1.tar.gz
    dest=/tmp/idea-2019.tar.gz
    validate_certs=no

- name: Unzip the thing
  become: no
  unarchive:
    src: /tmp/idea-2019.tar.gz
    dest: /tmp
    remote_src: yes

- name: move idea to expr
  become: no
  shell: mv /tmp/idea-IU-* ~/expr/idea-2019

- name: Link idea
  become: no
  file: src=~/expr/idea-2019/bin/idea.sh dest=~/bin/idea state=link force=yes
