---
- name: prepare expr/tmp directory
  become: no
  file:
    path: ~/expr/tmp
    state: directory

- name: Download intellij
  become: no
  get_url:
    url=https://download-cdn.jetbrains.com/idea/ideaIU-2022.1.2.tar.gz
    dest=~/expr/tmp/idea-2022.tar.gz
    validate_certs=no

- name: Unzip the thing
  become: no
  unarchive:
    src: ~/expr/tmp/idea-2022.tar.gz
    dest: ~/expr/tmp
    remote_src: yes

- name: move idea to expr
  become: no
  shell:
    cmd: mv ~/expr/tmp/idea-IU-* ~/expr/idea-2022
    creates: ~/expr/idea-2022

- name: Link idea
  become: no
  file:
    src: ~/expr/idea-2022/bin/idea.sh
    dest: ~/bin/idea
    state: link
    force: yes

- name: clean up expr/tmp directory
  become: no
  file:
    path: ~/expr/tmp
    state: absent
